### PR TITLE
Fix Portable AR-2 always having BLUFOR Camo

### PR DESCRIPTION
**Pull request by mrschick**
Some next additions could be:
- LDF drone variants, though that might be a hassle to script without creating portable drone items for individual factions;
- Civilian and IDAP AL-6 variants;

If you think the current fix is sufficient for a mod update, we can make some additional changes in this PR to update the build's version as well.

### CODE REVIEW

**Comment by mrschick** [comment]
When you have time to review feel free to delete the 2 branches `fix-ar2-camo` and `revert-5-fix-ar2-camo` (created by mistake), I don't have permission to do so.

**Comment by pastoman** [comment]
@mrschick is the main branch ready to be pushed to steam workshop?

**Comment by mrschick** [comment]
Yes, everything checks out.
You can download the HEMTT executable, run `hemtt.exe release` through the console and then use the Arma 3 Tools publisher to update the mod on the workshop with `.hemttout/release/`.

**Comment by pastoman** [comment]
@mrschick Thanks, btw. you could also add me on discord for more efficient communication: discord name: pastoman

**Comment by mrschick** [comment]
Ah, and before building the release maybe it's best to change the version in `addons/main/script_version.hpp` to the one you like.

Will do 👌🏻

**Pull request merged**
