### PR TITLE
HEMTT Build Tool Integration

### PR DESCRIPTION
**Pull request by mrschick**
Hi, I got almost everything working with HEMTT. All items exist, the config is included and the icons are visible in mission.

Only thing missing is that the functions are not properly read, i.e: when placing the AR2 the `EFUNC(common,progressBar)` function will be skipped, while any surrounding code will be executed.
Not yet sure what it's caused by, most likely `XEH_PREP.hpp` doesn't find or build the functions properly, or there's an issue with Ace inclusion.

### CODE REVIEW

**Comment by pastoman** [comment]
Ok, thanks, unfortunately I'm currently extremly busy with my studies, so you will probably have to sort it out by yourself, but I will aprove you the merge, and when it will be working I will build you an working addon. pbo rhat is signed that you can test if it works correctly. If it will be working then I will test it and publish it to steam workshop. I should have slightly more time in like 2 to 3 weeks.

**Comment by mrschick** [comment]
No problem, I'll figure it out.
You didn't have to merge it until it was complete and fully working though, now I'll have to make another PR just to fix this one.

**Comment by pastoman** [comment]
Yeah, don't worry about that, I'm planning on splitting current branch to dev and main.

**Comment by pastoman** [comment]
Ok main branch is where it was before merge and dev branch is with merge, so you can continue working on it.

**Comment by pastoman** [comment]
I've also added you as collaborator, because I don't currently have that much time, if you don't agree with it, you can just decline it.

**Comment by mrschick** [comment]
@pastoman Thanks for the collaborator role, I'll put it to good use.
Unfortunately it seems like the current branch protection rules prevent me from pushing to any branch and from creating any new branch.
In general I don't think a `dev` branch is really needed going forward, best practice is usually to create a branch for a fix or new feature, work on it, then create a pull request back into `main` that will be squash merged after a code review.

**Comment by pastoman** [comment]
@mrschick Now it should work for you, but you still won't be able to delete (I still don't know how to assign you bypass role so same goes for anyone)

**Comment by mrschick** [comment]
I guess you mean branch deletion, that's fine.
By default nobody has write access to the Repo anyway, the rules only apply to collaborators.

**Comment by pastoman** [comment]
Ok, I've disabled branch protection.

**Pull request merged**
